[project]
name = "pixbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Thomas Ammitzboll-Bach", email = "tab@uu.dk" }
]
requires-python = ">=3.12"
dependencies = [
    "cairosvg>=2.9.0",
    "drawsvg[all]>=2.4.1",
]

[build-system]
requires = ["uv_build>=0.10.6,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.13",
    "ty>=0.0.35",
]
[tool.ty.environment]
python = ".venv"
